#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=IIT_simglucose
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=4:00:00
#SBATCH --mem=60G
#SBATCH --output=outputs/slurm_output_%A.out
module purge
module load 2022
module load Anaconda3/2022.05
# Your job starts in the directory where you call sbatch
cd $HOME/IIT_simglucose/
source activate iit_simglucose
srun python3 -u main_MLP.py